# Describes the format for available services for web bolier

turn:
  name: Set boiler on or off
  description: >
    Turn boiler on or off
  fields:
    serial:
      description: >
        Serial of device.
      required: true
      selector:
        text:
    value:
      description: >
        true or false.
      required: true
      default: false
      selector:
        boolean:

turn_on:
  name: Set boiler on
  description: >
    Turn boiler on
  fields:
    serial:
      description: >
        Serial of device.
      required: true
      selector:
        text:

turn_off:
  name: Set boiler off
  description: >
    Turn boiler off
  fields:
    serial:
      description: >
        Serial of device.
      required: true
      selector:
        text:

turn_toggle:
  name: Toggle boiler on/off state
  description: >
    Toggle boiler on/off state
  fields:
    serial:
      description: >
        Serial of device.
      required: true
      selector:
        text:
