name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: request
    attributes:
      label: Requested feature
      description: Describe the behavior or entity you would like to add.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Use case
      description: Explain why this would be useful.
    validations:
      required: true
